
project_id = "zuhcmwujzfddmafozubd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[inbucket]
enabled = true

[storage]
enabled = true

[auth]
enabled = true

[studio]
enabled = true

[functions]
[functions.process-document]
verify_jwt = true

[functions.process-image]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true

[functions.generate-explanation]
verify_jwt = true

[functions.microsoft-auth]
verify_jwt = true
