
project_id = "zuhcmwujzfddmafozubd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[auth]
enabled = true
port = 54325

[realtime]
enabled = true

[storage]
enabled = true

[edge_functions]
[edge_functions.note-chat]
verify_jwt = true

[edge_functions.note-chat-streaming]
verify_jwt = true
