
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "zuhcmwujzfddmafozubd"
[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
[db]
port = 54322
[studio]
enabled = true
port = 54323
[inbucket]
enabled = true
port = 54324
[storage]
enabled = true
[auth]
enabled = true
[realtime]
enabled = true
[functions]
[functions.delete-note]
verify_jwt = true
[functions.send-note-email]
verify_jwt = true
