
import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { useAdaptiveSessionManager } from '@/hooks/useAdaptiveSessionManager';
import { usePredictiveLearning } from '@/hooks/usePredictiveLearning';
import { useRealTimeSessionTracker } from '@/hooks/useRealTimeSessionTracker';
import { Brain, Zap, Target, Clock, TrendingUp, AlertTriangle } from 'lucide-react';

interface AutoGeneratedSession {
  title: string;
  topic: string;
  duration: number;
  difficulty: number;
  type: 'review' | 'learn' | 'practice' | 'remediation';
  reason: string;
  priority: 'low' | 'medium' | 'high';
  scheduledFor: Date;
}

export const SessionOrchestrator = () => {
  const { recommendations, adaptations, applyRecommendation, dismissRecommendation } = useAdaptiveSessionManager();
  const { predictions, learningVelocity, getPersonalizedRecommendations } = usePredictiveLearning();
  const { metrics, isTracking } = useRealTimeSessionTracker();
  
  const [autoGeneratedSessions, setAutoGeneratedSessions] = useState<AutoGeneratedSession[]>([]);
  const [orchestrationEnabled, setOrchestrationEnabled] = useState(true);

  // Auto-generate follow-up sessions based on performance
  useEffect(() => {
    if (!predictions || !orchestrationEnabled) return;

    const newSessions: AutoGeneratedSession[] = [];

    // Generate remediation sessions for knowledge gaps
    predictions.knowledgeGaps.forEach(topic => {
      const tomorrow = new Date();
      tomorrow.setDate(tomorrow.getDate() + 1);
      
      newSessions.push({
        title: `Remediation: ${topic}`,
        topic,
        duration: 30,
        difficulty: 2, // Lower difficulty for remediation
        type: 'remediation',
        reason: 'Address identified knowledge gap',
        priority: 'high',
        scheduledFor: tomorrow,
      });
    });

    // Generate review sessions based on spaced repetition
    predictions.reviewSchedule.slice(0, 3).forEach(review => {
      newSessions.push({
        title: `Review: ${review.topic}`,
        topic: review.topic,
        duration: 20,
        difficulty: 3,
        type: 'review',
        reason: review.reason,
        priority: review.priority,
        scheduledFor: review.date,
      });
    });

    // Generate learning sessions for optimal next topics
    predictions.optimalNextTopics.slice(0, 2).forEach(topic => {
      const nextWeek = new Date();
      nextWeek.setDate(nextWeek.getDate() + 7);
      
      newSessions.push({
        title: `Learn: ${topic}`,
        topic,
        duration: 45,
        difficulty: adaptations.difficultyLevel,
        type: 'learn',
        reason: 'Optimal topic for current skill level',
        priority: 'medium',
        scheduledFor: nextWeek,
      });
    });

    setAutoGeneratedSessions(newSessions.slice(0, 5)); // Limit to 5 sessions
  }, [predictions, adaptations.difficultyLevel, orchestrationEnabled]);

  const handleApplyRecommendation = (recommendation: any) => {
    applyRecommendation(recommendation);
  };

  const getUrgencyColor = (urgency: string) => {
    switch (urgency) {
      case 'high': return 'text-red-600 bg-red-50 border-red-200';
      case 'medium': return 'text-yellow-600 bg-yellow-50 border-yellow-200';
      default: return 'text-blue-600 bg-blue-50 border-blue-200';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return 'bg-red-100 text-red-800';
      case 'medium': return 'bg-yellow-100 text-yellow-800';
      default: return 'bg-green-100 text-green-800';
    }
  };

  if (!isTracking) {
    return (
      <Card>
        <CardContent className="p-6 text-center">
          <Brain className="h-12 w-12 mx-auto text-gray-400 mb-4" />
          <p className="text-gray-600">
            Start a study session to activate intelligent orchestration
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      {/* Real-Time Recommendations */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Zap className="h-5 w-5 text-blue-600" />
            Live Recommendations
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {recommendations.length === 0 ? (
            <div className="text-center py-4">
              <TrendingUp className="h-8 w-8 mx-auto text-green-500 mb-2" />
              <p className="text-sm text-gray-600">You're doing great! No adjustments needed.</p>
            </div>
          ) : (
            recommendations.map((rec, index) => (
              <div
                key={index}
                className={`p-4 rounded-lg border ${getUrgencyColor(rec.urgency)}`}
              >
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-2">
                      {rec.type === 'difficulty_adjust' && <Target className="h-4 w-4" />}
                      {rec.type === 'break_insert' && <Clock className="h-4 w-4" />}
                      {rec.type === 'topic_switch' && <Brain className="h-4 w-4" />}
                      {rec.type === 'encouragement' && <TrendingUp className="h-4 w-4" />}
                      <Badge variant="outline" className="text-xs">
                        {rec.urgency} priority
                      </Badge>
                    </div>
                    <p className="text-sm font-medium">{rec.message}</p>
                  </div>
                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      onClick={() => handleApplyRecommendation(rec)}
                      className="h-7 px-3 text-xs"
                    >
                      Apply
                    </Button>
                    <Button
                      size="sm"
                      variant="ghost"
                      onClick={() => dismissRecommendation(rec)}
                      className="h-7 px-3 text-xs"
                    >
                      Dismiss
                    </Button>
                  </div>
                </div>
              </div>
            ))
          )}
        </CardContent>
      </Card>

      {/* Auto-Generated Sessions */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Brain className="h-5 w-5 text-purple-600" />
            Smart Session Planning
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium">Auto-Orchestration</span>
            <Button
              size="sm"
              variant={orchestrationEnabled ? "default" : "outline"}
              onClick={() => setOrchestrationEnabled(!orchestrationEnabled)}
              className="h-7 px-3 text-xs"
            >
              {orchestrationEnabled ? 'ON' : 'OFF'}
            </Button>
          </div>

          {autoGeneratedSessions.length === 0 ? (
            <div className="text-center py-4">
              <AlertTriangle className="h-8 w-8 mx-auto text-gray-400 mb-2" />
              <p className="text-sm text-gray-600">
                Complete more sessions to unlock smart planning
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              {autoGeneratedSessions.map((session, index) => (
                <div
                  key={index}
                  className="p-3 bg-gray-50 rounded-lg border"
                >
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-sm font-medium">{session.title}</span>
                        <Badge className={getPriorityColor(session.priority)}>
                          {session.priority}
                        </Badge>
                      </div>
                      <p className="text-xs text-gray-600 mb-2">{session.reason}</p>
                      <div className="flex items-center gap-4 text-xs text-gray-500">
                        <span>{session.duration}min</span>
                        <span>Difficulty: {session.difficulty}/5</span>
                        <span>{session.scheduledFor.toLocaleDateString()}</span>
                      </div>
                    </div>
                    <Button size="sm" variant="outline" className="h-7 px-3 text-xs">
                      Schedule
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Performance Insights */}
      <Card className="lg:col-span-2">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-green-600" />
            Learning Intelligence Dashboard
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="text-center">
              <div className="text-2xl font-bold text-blue-600">
                {Math.round(metrics.focusLevel)}%
              </div>
              <div className="text-sm text-gray-600">Focus Level</div>
            </div>
            
            <div className="text-center">
              <div className="text-2xl font-bold text-purple-600">
                {Math.round(learningVelocity.current)}
              </div>
              <div className="text-sm text-gray-600">Cards/Hour</div>
            </div>
            
            <div className="text-center">
              <div className="text-2xl font-bold text-green-600">
                {Math.round(metrics.accuracyRate)}%
              </div>
              <div className="text-sm text-gray-600">Accuracy</div>
            </div>
            
            <div className="text-center">
              <div className="text-2xl font-bold text-orange-600">
                {adaptations.difficultyLevel}/5
              </div>
              <div className="text-sm text-gray-600">Difficulty</div>
            </div>
          </div>

          {predictions && (
            <div className="mt-6 pt-4 border-t">
              <h4 className="text-sm font-medium mb-3">Personalized Insights</h4>
              <div className="grid gap-2">
                {getPersonalizedRecommendations().map((insight, index) => (
                  <div key={index} className="text-sm text-gray-600 flex items-center gap-2">
                    <div className="w-2 h-2 bg-blue-500 rounded-full" />
                    {insight.message}
                  </div>
                ))}
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};
